"""Add custom percent access fields to User model

Revision ID: 825b71c50eab
Revises: c5e55da5458d
Create Date: 2025-04-05 23:31:56.582990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825b71c50eab'
down_revision = 'c5e55da5458d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_predefined_percent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_use_custom_percent', sa.Boolean(), nullable=True))
        batch_op.drop_column('can_view_percent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_percent', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('can_use_custom_percent')
        batch_op.drop_column('can_view_predefined_percent')

    # ### end Alembic commands ###
